language: python
python:
  - 3.5
install:
  - travis_retry pip install babel reportlab
  - travis_retry python setup.py
  - travis_retry python setup.py install
script:
  - env WCG_TEST_DRIVERS=reportlab python setup.py test
