# We require sudo until Travis CI let us add the de_DE.utf8 locale in
# a better way.
sudo: required

language: python

python:
  - 3.5

before_install:
  - sudo locale-gen de_DE.utf8
  - locale -a
  - locale

install:
  - travis_retry pip install babel reportlab
  - travis_retry python -m locale

script:
  - travis_retry python setup.py build
  - travis_retry python setup.py install
  - travis_retry env WCG_TEST_DRIVERS=reportlab python setup.py test
